name: Update Latest Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  Latest-Build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1

    - name: Build with npm
      uses: actions/setup-node@v4.2.0
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run build

    - name: ZIP Executable
      uses: vimtor/action-zip@v1.2
      with:
        files: build/_h5ai
        dest: _h5ai.zip

    - name: Upload Release Build
      uses: WebFreak001/deploy-nightly@v3.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: https://uploads.github.com/repos/LilCatLily/h5ai/releases/197108083/assets{?name,label}
        release_id: 197108083
        asset_path: ./_h5ai.zip
        asset_name: _h5ai.zip
        asset_content_type: application/zip
        max_releases: 1

    - name: Update Release
      uses: richardsimko/update-tag@v1.0.11
      with:
        tag_name: 'latest'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
